require 'azure_media_service/model/base'
require 'azure_media_service/model/asset'
require 'azure_media_service/model/access_policy'
require 'azure_media_service/model/locator'
require 'azure_media_service/model/asset_file'
require 'azure_media_service/model/media_processor'
require 'azure_media_service/model/job'
